<?php

/**
 * Implements hook_preprocess_html().
 *
 * Adds the PREVIEW indicator.
 */
function headless_preview_preprocess_html(&$variables) {
  $route_name = \Drupal::routeMatch()->getRouteName();

  if ($route_name === 'entity.node.canonical') {
    /** @var \Drupal\node\Entity\Node $node */
    $node = \Drupal::routeMatch()->getParameter('node');
    $variables['page']['#attached']['library'][] = 'headless_preview/frontend-iframe';

    if (!$node->isPublished()) {
      // Add class to show "PREVIEW" text next to the title.
      $variables['page']['header']['burst_theme_page_title']['#attributes']['class'][] = 'page-title--preview';
    }
  }
}
